backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
collections:
  - name: config
    label: Config
    delete: false
    editor:
      preview: false
    files:
      - name: general
        label: Site Config
        file: config.json
        description: General site settings
        fields:
          - label: URL
            name: base_url
            widget: string
            hint: Do not enter the trailing slash of the URL
          - label: Site title
            name: site_title
            widget: string
          - label: Site description
            name: site_description
            widget: string
          - label: Twitter account
            name: twitter_account
            widget: string
            required: false
            hint: ""
            default: ""
          - label: GitHub account
            name: github_account
            widget: string
            required: false
            hint: ""
            default: ""
          - label: Instagram Account
            name: instagram_account
            required: false
            widget: string
            hint: ""
            default: ""
          - label: LinkedIn accoun
            name: linkedin_account
            required: false
            widget: string
            hint: ""
            default: ""
          - label: Site keywords
            name: site_keywords
            widget: list
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: string
